project:
  type: website
  output-dir: docs

website:
  title: "Climate and Ocean Modeling Workshop â€“ SB5"
  navbar:
    left:
      - text: "ğŸ  Home"
        file: 01_home.qmd
      - text: "ğŸ‘¥ Participants"
        file: participants/01_participants.qmd
      - text: "ğŸ“ Workshop Logistics"
        file: logistics/01_logistics.qmd
      - text: "ğŸ“‚ Materials"
        file: resources/materials.qmd

  sidebar:
    style: docked
    contents:
      - section: "Daily Schedule"
        contents:
          - agenda/day1.qmd
          - agenda/day2.qmd
          - agenda/day3.qmd
          - agenda/day4.qmd
  page-footer:
    left: "Â© 2025 Isaac Brito-Morales"
    right: "Save the Blue 5"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: article
    grid:
      sidebar-width: 280px
      body-width: 720px
    lang: en